### ISSUE TITLE
Compilation error after mix deps.update

### ISSUE THREAD

**Issue by WernerBuchert** [elixir-cldr/cldr_calendars#21]
Good morning,

i have a phoenix project and i'm using Elixir 1.16.2 (compiled with Erlang/OTP 26).
After calling "mix deps.update -all" there was an upgrade:

ex_cldr_calendars 1.23.1 => 1.24.0

Now my project doesn't compile anymore, there seems to be a bug:

 error: Duration.__struct__/0 is undefined, cannot expand struct Duration. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
      │
 2902 │   defp shift_date_options(%Duration{
      │                           ^
      │
      └─ lib/cldr/calendar.ex:2902:27: Cldr.Calendar.shift_date_options/1

== Compilation error in file lib/cldr/calendar.ex ==
** (CompileError) lib/cldr/calendar.ex: cannot compile module Cldr.Calendar (errors have been logged)
    lib/cldr/calendar.ex:2902: (module)

Thanks for your library!
Best regards,
Werner.

**Comment by kipcole9** [comment]
I've published [ex_cldr_calendars version 1.24.1](https://hex.pm/packages/ex_cldr_calendars/1.24.1) with the following changeling entry:

### Bug Fixes

* Compile on Elixir releases < 1.17. Some code in `Cldr.Calendar` depends on the new `t:Duration.t/0` struct which is only available on Elixir 1.17 or later. Elixir 1.16 is now added to the CI test matrix to ensure no future regression. Thanks to @WernerBuchert for the report. Closes #21.

Thanks again for the report and apologies for this morning's inconvenience.
